#!/usr/bin/env python3
"""
NYC Open Data Cyclical Pattern Analysis
Analyzes 311 Service Requests, Rodent Inspections, and MTA Ridership for seasonal patterns.

Output: cyclical_report.md — STL seasonal strength scores per dataset/complaint type.

Abundance CSVs (prophecy-source-data/*_abundance.csv):
    Generated by a separate script (not this one). Each file contains one row per day
    for the full year 2024, with an 'abundance' column classifying the daily count into
    one of five ordinal levels. See assign_abundance() below for the categorization logic.
"""

import requests
import pandas as pd
import numpy as np
from statsmodels.tsa.seasonal import STL
import warnings
import json
from datetime import datetime

warnings.filterwarnings('ignore')

BASE_URL = "https://data.cityofnewyork.us/resource"

def fetch_data(url, desc=""):
    """Fetch data from Socrata API without auth token."""
    print(f"  Fetching: {desc or url[:80]}")
    try:
        resp = requests.get(url, timeout=60)
        resp.raise_for_status()
        data = resp.json()
        print(f"    -> Got {len(data)} rows")
        return data
    except Exception as e:
        print(f"    -> ERROR: {e}")
        return None

def compute_stl_strength(series_values, period=12):
    """
    Compute STL seasonal strength.
    Returns strength in [0, 1] where 1 = perfectly seasonal.
    """
    if len(series_values) < period * 2:
        return None
    s = pd.Series(series_values, dtype=float)
    s = s.dropna()
    if len(s) < period * 2:
        return None
    try:
        stl = STL(s, period=period, robust=True)
        res = stl.fit()
        var_resid = np.var(res.resid)
        var_seas_resid = np.var(res.seasonal + res.resid)
        if var_seas_resid == 0:
            return 0.0
        strength = max(0, 1 - var_resid / var_seas_resid)
        return round(strength, 4)
    except Exception as e:
        print(f"    STL error: {e}")
        return None

def peak_month_index(series_values, period=12, date_index=None):
    """
    Find the peak calendar month (1-12) of the STL seasonal component.
    date_index: optional DatetimeIndex aligned with series_values — used to
    group seasonal component by actual calendar month rather than series position.
    """
    if len(series_values) < period * 2:
        return None
    s = pd.Series(series_values, dtype=float)
    s = s.dropna()
    if len(s) < period * 2:
        return None
    try:
        stl = STL(s, period=period, robust=True)
        res = stl.fit()
        if date_index is not None and len(date_index) == len(res.seasonal):
            # Use .values to avoid pandas label-alignment (res.seasonal has RangeIndex)
            seas_with_dates = pd.Series(res.seasonal.values, index=date_index)
            monthly_avgs = seas_with_dates.groupby(seas_with_dates.index.month).mean()
            return int(monthly_avgs.idxmax())
        else:
            # Fallback: positional grouping (only accurate if series starts in Jan)
            seas = pd.Series(res.seasonal)
            month_avg = [seas[i::12].mean() for i in range(12)]
            return month_avg.index(max(month_avg)) + 1
    except:
        return None

MONTH_NAMES = {1:'Jan',2:'Feb',3:'Mar',4:'Apr',5:'May',6:'Jun',
               7:'Jul',8:'Aug',9:'Sep',10:'Oct',11:'Nov',12:'Dec'}

def month_label(m):
    if m is None:
        return "N/A"
    return MONTH_NAMES.get(m, str(m))

def assign_abundance(daily_counts):
    """
    Classify daily counts into five ordinal abundance levels using quintile breaks.

    This is the categorization used in prophecy-source-data/*_abundance.csv. Thresholds
    are computed from the full-year distribution of the specific dataset being classified,
    so labels are relative within each dataset (not cross-dataset).

    Bins (quintiles of the input series):
        Very Low  : 0th–20th percentile
        Low       : 20th–40th percentile
        Medium    : 40th–60th percentile
        High      : 60th–80th percentile
        Very High : 80th–100th percentile

    Ties at a boundary are assigned to the lower bin. Example for dog bites 2024 (n=366):
        Very Low  <= 8   (P20=8;  n=101 including ties)
        Low        9–10  (P40=10; n=73)
        Medium    11–12  (P60=12; n=67)
        High      13–14  (P80=14; n=56)
        Very High >= 15  (n=69)

    Equivalent pandas one-liner:
        pd.qcut(series, q=5, labels=['Very Low','Low','Medium','High','Very High'])
    """
    vals = list(daily_counts)
    n = len(vals)
    s = sorted(vals)
    t = [s[int(n * p / 100)] for p in (20, 40, 60, 80)]  # P20, P40, P60, P80
    bins = ["Very Low", "Low", "Medium", "High", "Very High"]
    return [
        bins[0] if v <= t[0] else
        bins[1] if v <= t[1] else
        bins[2] if v <= t[2] else
        bins[3] if v <= t[3] else
        bins[4]
        for v in vals
    ]


def season_desc(month_num):
    if month_num is None:
        return "N/A"
    if month_num in [12, 1, 2]:
        return "peaks in winter"
    elif month_num in [3, 4, 5]:
        return "peaks in spring"
    elif month_num in [6, 7, 8]:
        return "peaks in summer"
    elif month_num in [9, 10, 11]:
        return "peaks in fall"
    return "N/A"

# ============================================================
# SECTION 1: 311 Service Requests
# ============================================================
print("\n" + "="*60)
print("SECTION 1: 311 Service Requests")
print("="*60)

url_311_agency = (
    f"{BASE_URL}/erm2-nwe9.json"
    "?$select=date_trunc_ym(created_date)%20as%20month,agency,count(*)%20as%20n"
    "&$group=date_trunc_ym(created_date),agency"
    "&$order=date_trunc_ym(created_date)"
    "&$limit=5000"
    "&$where=created_date%20%3E%3D%20'2015-01-01'"
)

raw_agency = fetch_data(url_311_agency, "311 monthly by agency")

agency_results = []
if raw_agency:
    df_agency = pd.DataFrame(raw_agency)
    df_agency['n'] = pd.to_numeric(df_agency['n'], errors='coerce')
    df_agency['month'] = pd.to_datetime(df_agency['month'], errors='coerce')
    df_agency = df_agency.dropna(subset=['month', 'n'])
    df_agency = df_agency.sort_values('month')

    agencies = df_agency['agency'].unique()
    print(f"  Found {len(agencies)} agencies")

    for ag in agencies:
        sub = df_agency[df_agency['agency'] == ag].copy()
        sub = sub.set_index('month').sort_index()
        full_idx = pd.date_range(sub.index.min(), sub.index.max(), freq='MS')
        sub = sub.reindex(full_idx)['n']

        n_months = sub.notna().sum()
        sparsity = sub.isna().sum() / len(sub)

        if n_months >= 36 and sparsity < 0.3:
            filled = sub.fillna(sub.median())
            vals = filled.values
            strength = compute_stl_strength(vals, period=12)
            pk = peak_month_index(vals, period=12, date_index=filled.index)
            if strength is not None:
                agency_results.append({
                    'agency': ag,
                    'n_months': n_months,
                    'total_requests': int(sub.sum()),
                    'seasonal_strength': strength,
                    'peak_month': month_label(pk),
                    'pattern': season_desc(pk)
                })

    agency_results = sorted(agency_results, key=lambda x: x['seasonal_strength'], reverse=True)
    print(f"  Scored {len(agency_results)} agencies")

url_311_ctypes = (
    f"{BASE_URL}/erm2-nwe9.json"
    "?$select=complaint_type,count(*)%20as%20n"
    "&$group=complaint_type"
    "&$order=n%20DESC"
    "&$limit=15"
    "&$where=created_date%20%3E%3D%20'2015-01-01'"
)

raw_ctypes = fetch_data(url_311_ctypes, "311 top complaint types")

complaint_results = []
if raw_ctypes:
    df_ctypes = pd.DataFrame(raw_ctypes)
    df_ctypes['n'] = pd.to_numeric(df_ctypes['n'], errors='coerce')
    top_complaints = df_ctypes.dropna(subset=['n']).head(15)['complaint_type'].tolist()
    print(f"  Top 5 complaint types: {top_complaints[:5]}")

    for ct in top_complaints:
        ct_encoded = requests.utils.quote(ct)
        url_ct = (
            f"{BASE_URL}/erm2-nwe9.json"
            f"?$select=date_trunc_ym(created_date)%20as%20month,count(*)%20as%20n"
            f"&$group=date_trunc_ym(created_date)"
            f"&$order=date_trunc_ym(created_date)"
            f"&$limit=500"
            f"&$where=created_date%20%3E%3D%20'2015-01-01'%20AND%20complaint_type%3D'{ct_encoded}'"
        )
        raw_ct = fetch_data(url_ct, f"complaint type: {ct[:40]}")
        if raw_ct and len(raw_ct) >= 12:
            df_ct = pd.DataFrame(raw_ct)
            df_ct['n'] = pd.to_numeric(df_ct['n'], errors='coerce')
            df_ct['month'] = pd.to_datetime(df_ct['month'], errors='coerce')
            df_ct = df_ct.dropna().sort_values('month')
            full_idx = pd.date_range(df_ct['month'].min(), df_ct['month'].max(), freq='MS')
            s = df_ct.set_index('month')['n'].reindex(full_idx).fillna(0)
            if len(s) >= 24:
                strength = compute_stl_strength(s.values, period=12)
                pk = peak_month_index(s.values, period=12, date_index=s.index)
                total = int(df_ctypes[df_ctypes['complaint_type']==ct]['n'].iloc[0])
                complaint_results.append({
                    'complaint_type': ct,
                    'total_volume': total,
                    'n_months': len(s),
                    'seasonal_strength': strength if strength is not None else 0,
                    'peak_month': month_label(pk),
                    'pattern': season_desc(pk)
                })

    complaint_results = sorted(complaint_results, key=lambda x: x['seasonal_strength'], reverse=True)
    print(f"  Scored {len(complaint_results)} complaint types")

# ============================================================
# SECTION 2: Rodent Inspections
# ============================================================
print("\n" + "="*60)
print("SECTION 2: Rodent Inspections")
print("="*60)

url_rodent_schema = f"{BASE_URL}/p937-wjvj.json?$limit=3"
raw_rodent_schema = fetch_data(url_rodent_schema, "Rodent schema sample")
rodent_fields = list(raw_rodent_schema[0].keys()) if raw_rodent_schema else []
print(f"  Fields: {rodent_fields[:10]}...")

url_rodent_monthly = (
    f"{BASE_URL}/p937-wjvj.json"
    "?$select=date_trunc_ym(inspection_date)%20as%20month,count(*)%20as%20n"
    "&$group=date_trunc_ym(inspection_date)"
    "&$order=date_trunc_ym(inspection_date)"
    "&$limit=500"
)

raw_rodent_monthly = fetch_data(url_rodent_monthly, "Rodent monthly counts")
rodent_monthly_strength = None
rodent_peak = None
rodent_monthly_data = None

if raw_rodent_monthly:
    df_rod_m = pd.DataFrame(raw_rodent_monthly)
    df_rod_m['n'] = pd.to_numeric(df_rod_m['n'], errors='coerce')
    df_rod_m['month'] = pd.to_datetime(df_rod_m['month'], errors='coerce')
    df_rod_m = df_rod_m.dropna().sort_values('month')
    rodent_monthly_data = df_rod_m
    full_idx = pd.date_range(df_rod_m['month'].min(), df_rod_m['month'].max(), freq='MS')
    s_rod = df_rod_m.set_index('month')['n'].reindex(full_idx).fillna(df_rod_m['n'].median())
    if len(s_rod) >= 24:
        rodent_monthly_strength = compute_stl_strength(s_rod.values, period=12)
        rodent_peak = peak_month_index(s_rod.values, period=12, date_index=s_rod.index)
        print(f"  Monthly STL strength: {rodent_monthly_strength}, peak: {month_label(rodent_peak)}")

url_rodent_dow = (
    f"{BASE_URL}/p937-wjvj.json"
    "?$select=date_extract_dow(inspection_date)%20as%20dow,count(*)%20as%20n"
    "&$group=date_extract_dow(inspection_date)"
    "&$order=date_extract_dow(inspection_date)"
    "&$limit=10"
)

raw_rodent_dow = fetch_data(url_rodent_dow, "Rodent day-of-week counts")
rodent_dow_data = None
DOW_NAMES = {0:'Sun',1:'Mon',2:'Tue',3:'Wed',4:'Thu',5:'Fri',6:'Sat'}

if raw_rodent_dow:
    df_rod_dow = pd.DataFrame(raw_rodent_dow)
    df_rod_dow['dow'] = pd.to_numeric(df_rod_dow['dow'], errors='coerce')
    df_rod_dow['n'] = pd.to_numeric(df_rod_dow['n'], errors='coerce')
    df_rod_dow = df_rod_dow.dropna().sort_values('dow')
    df_rod_dow['day_name'] = df_rod_dow['dow'].map(lambda x: DOW_NAMES.get(int(x), str(x)))
    rodent_dow_data = df_rod_dow
    print("  DOW data:")
    print(df_rod_dow[['day_name','n']].to_string())

rodent_has_result = 'result' in rodent_fields

# ============================================================
# SECTION 3: MTA Ridership
# ============================================================
print("\n" + "="*60)
print("SECTION 3: MTA Ridership")
print("="*60)

# MTA Daily Ridership is on data.ny.gov
MTA_DATASET_ID = "vxuj-8kew"
MTA_DOMAIN = "data.ny.gov"
MTA_NAME = "MTA Daily Ridership Data: 2020-2025"

mta_modes = {
    'subways_total_estimated_ridership': 'Subway',
    'buses_total_estimated_ridersip': 'Bus',
    'lirr_total_estimated_ridership': 'LIRR',
    'metro_north_total_estimated_ridership': 'Metro-North',
    'access_a_ride_total_scheduled_trips': 'Access-A-Ride',
    'bridges_and_tunnels_total_traffic': 'Bridges & Tunnels',
    'staten_island_railway_total_estimated_ridership': 'Staten Island Railway',
}

mta_results = []
mta_error = None

# Fetch raw daily data and aggregate monthly ourselves
url_mta_all = f"https://{MTA_DOMAIN}/resource/{MTA_DATASET_ID}.json?$limit=50000&$order=date"
raw_mta_all = fetch_data(url_mta_all, f"MTA daily ridership (all rows)")

if raw_mta_all:
    df_mta_raw = pd.DataFrame(raw_mta_all)
    df_mta_raw['date'] = pd.to_datetime(df_mta_raw['date'], errors='coerce')
    df_mta_raw = df_mta_raw.dropna(subset=['date'])
    df_mta_raw['month'] = df_mta_raw['date'].dt.to_period('M').dt.to_timestamp()

    # Convert mode columns to numeric
    for col in mta_modes:
        if col in df_mta_raw.columns:
            df_mta_raw[col] = pd.to_numeric(df_mta_raw[col], errors='coerce')

    print(f"  MTA raw data: {len(df_mta_raw)} rows, {df_mta_raw['date'].min().date()} to {df_mta_raw['date'].max().date()}")

    # Monthly aggregation
    monthly_cols = [col for col in mta_modes if col in df_mta_raw.columns]
    df_mta_monthly = df_mta_raw.groupby('month')[monthly_cols].sum().reset_index()
    df_mta_monthly = df_mta_monthly.sort_values('month')

    # Remove months with very low total (likely partial months)
    for col in monthly_cols:
        field_name = mta_modes[col]
        s = df_mta_monthly.set_index('month')[col]
        full_idx = pd.date_range(s.index.min(), s.index.max(), freq='MS')
        s = s.reindex(full_idx)

        # Drop first and last month (often partial)
        s = s.iloc[1:-1]
        s = s.fillna(s.median())

        if len(s) >= 24:
            strength = compute_stl_strength(s.values, period=12)
            pk = peak_month_index(s.values, period=12, date_index=s.index)
            mta_results.append({
                'mode': field_name,
                'field': col,
                'n_months': len(s),
                'seasonal_strength': strength,
                'peak_month': month_label(pk),
                'pattern': season_desc(pk),
                'total': float(s.sum())
            })
            print(f"  {field_name}: strength={strength}, peak={month_label(pk)}, months={len(s)}")
        else:
            print(f"  {field_name}: only {len(s)} months, skipping")
else:
    mta_error = f"Could not fetch MTA dataset {MTA_DATASET_ID} from {MTA_DOMAIN}"

mta_results_sorted = sorted([r for r in mta_results if r['seasonal_strength'] is not None],
                             key=lambda x: x['seasonal_strength'], reverse=True)

# Also get NYC Ferry (on data.cityofnewyork.us)
print("\n  Fetching NYC Ferry ridership...")
url_ferry_monthly = (
    "https://data.cityofnewyork.us/resource/t5n6-gx8c.json"
    "?$select=date_trunc_ym(date)%20as%20month,sum(boardings)%20as%20total"
    "&$group=date_trunc_ym(date)"
    "&$order=date_trunc_ym(date)"
    "&$limit=500"
)
raw_ferry = fetch_data(url_ferry_monthly, "NYC Ferry monthly boardings")
ferry_strength = None
ferry_peak = None
ferry_months = 0

if raw_ferry:
    df_ferry = pd.DataFrame(raw_ferry)
    df_ferry['total'] = pd.to_numeric(df_ferry['total'], errors='coerce')
    df_ferry['month'] = pd.to_datetime(df_ferry['month'], errors='coerce')
    df_ferry = df_ferry.dropna().sort_values('month')
    full_idx = pd.date_range(df_ferry['month'].min(), df_ferry['month'].max(), freq='MS')
    s_ferry = df_ferry.set_index('month')['total'].reindex(full_idx)
    s_ferry = s_ferry.iloc[1:-1].fillna(s_ferry.median())
    ferry_months = len(s_ferry)
    if len(s_ferry) >= 24:
        ferry_strength = compute_stl_strength(s_ferry.values, period=12)
        ferry_peak = peak_month_index(s_ferry.values, period=12, date_index=s_ferry.index)
        print(f"  Ferry: strength={ferry_strength}, peak={month_label(ferry_peak)}")

# ============================================================
# COMPILE REPORT
# ============================================================
print("\n" + "="*60)
print("COMPILING REPORT")
print("="*60)

now_str = datetime.now().strftime("%Y-%m-%d")

lines = []
lines.append("# NYC Open Data: Cyclical Pattern Analysis")
lines.append(f"\n**Report generated:** {now_str}  ")
lines.append("**Analysis period:** 2015 to present (311/Rodent); 2020-2025 (MTA)  ")
lines.append("**Method:** STL decomposition (Seasonal-Trend decomposition using LOESS), period=12 months  ")
lines.append("**Seasonal strength:** ranges 0 (no seasonality) to 1 (perfectly seasonal)\n")
lines.append("---\n")

# ---- 311 ----
lines.append("## 1. 311 Service Requests\n")
lines.append("**Dataset:** `erm2-nwe9` — 311 Service Requests from 2010 to Present  ")
lines.append("**API:** data.cityofnewyork.us  ")
lines.append("**Scope:** 2015-01-01 onward\n")

if agency_results:
    lines.append("### 1.1 Agencies Ranked by Seasonal Strength\n")
    lines.append("Agencies with >= 36 months of data and < 30% missing months are included.\n")
    lines.append("| Rank | Agency | Total Requests | Months | Seasonal Strength | Peak Month | Pattern |")
    lines.append("|------|--------|----------------|--------|-------------------|------------|---------|")
    for i, row in enumerate(agency_results, 1):
        if row['seasonal_strength'] >= 0.5:
            tag = " **HIGH**"
        elif row['seasonal_strength'] >= 0.2:
            tag = " MED"
        else:
            tag = " low"
        lines.append(
            f"| {i} | {row['agency']} | {row['total_requests']:,} | {row['n_months']} "
            f"| {row['seasonal_strength']:.3f}{tag} | {row['peak_month']} | {row['pattern']} |"
        )

    high_seasonal = [r for r in agency_results if r['seasonal_strength'] >= 0.5]
    if high_seasonal:
        lines.append(f"\n**Highly seasonal agencies (strength >= 0.5):**\n")
        for r in high_seasonal:
            lines.append(
                f"- **{r['agency']}** (strength {r['seasonal_strength']:.3f}): "
                f"{r['pattern']} (peak: {r['peak_month']}), "
                f"{r['total_requests']:,} total requests over {r['n_months']} months"
            )
else:
    lines.append("*Could not compute agency seasonality.*\n")

if complaint_results:
    lines.append("\n### 1.2 Complaint Types Ranked by Seasonal Strength\n")
    lines.append("Top 15 complaint types by total volume, scored for monthly seasonality.\n")
    lines.append("| Rank | Complaint Type | Total Volume | Months | Seasonal Strength | Peak Month | Pattern |")
    lines.append("|------|----------------|--------------|--------|-------------------|------------|---------|")
    for i, row in enumerate(complaint_results, 1):
        if row['seasonal_strength'] >= 0.5:
            tag = " **HIGH**"
        elif row['seasonal_strength'] >= 0.2:
            tag = " MED"
        else:
            tag = " low"
        lines.append(
            f"| {i} | {row['complaint_type']} | {row['total_volume']:,} | {row['n_months']} "
            f"| {row['seasonal_strength']:.3f}{tag} | {row['peak_month']} | {row['pattern']} |"
        )

    lines.append("\n**Notable seasonal complaint patterns:**\n")
    for row in complaint_results[:8]:
        note = ""
        if row['complaint_type'] == 'HEAT/HOT WATER':
            note = " — tenants report heating failures when landlords turn off heat in cold months"
        elif 'Noise' in row['complaint_type']:
            note = " — outdoor activity, bars, and events drive warm-weather noise complaints"
        elif row['complaint_type'] == 'Water System':
            note = " — summer heat increases water usage and pipe stress"
        elif row['complaint_type'] == 'Street Condition':
            note = " — winter freeze-thaw cycles cause post-winter pothole surge"
        elif row['complaint_type'] == 'UNSANITARY CONDITION':
            note = " — warm weather accelerates waste decomposition and odor"
        lines.append(
            f"- **{row['complaint_type']}** (strength {row['seasonal_strength']:.3f}): "
            f"{row['pattern']} (peak: {row['peak_month']}){note}"
        )
else:
    lines.append("\n*Could not compute complaint type seasonality.*\n")

# ---- RODENTS ----
lines.append("\n---\n")
lines.append("## 2. Rodent Inspections\n")
lines.append("**Dataset:** `p937-wjvj` — Rodent Inspection Results  ")
lines.append("**API:** data.cityofnewyork.us\n")

if rodent_fields:
    key_fields = [f for f in rodent_fields if not f.startswith(':@')]
    lines.append(f"**Key fields available:** {', '.join(key_fields)}\n")

lines.append("### 2.1 Monthly Seasonality\n")
if rodent_monthly_strength is not None:
    if rodent_monthly_strength >= 0.5:
        strength_label = "HIGH"
    elif rodent_monthly_strength >= 0.2:
        strength_label = "MODERATE"
    else:
        strength_label = "LOW"

    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| STL Seasonal Strength | **{rodent_monthly_strength:.3f}** ({strength_label}) |")
    lines.append(f"| Peak Month | {month_label(rodent_peak)} |")
    lines.append(f"| Seasonal Pattern | {season_desc(rodent_peak)} |")
    if rodent_monthly_data is not None:
        lines.append(f"| Date Range | {rodent_monthly_data['month'].min().strftime('%Y-%m')} to {rodent_monthly_data['month'].max().strftime('%Y-%m')} |")
        lines.append(f"| Months of Data | {len(rodent_monthly_data)} |")
        lines.append(f"| Total Inspections | {int(rodent_monthly_data['n'].sum()):,} |")

    lines.append(f"\nRodent inspections show **{strength_label.lower()}** monthly seasonality "
                 f"(STL strength {rodent_monthly_strength:.3f}), {season_desc(rodent_peak)}. "
                 f"The relatively weak seasonal signal suggests that NYC's inspection schedule is "
                 f"largely standardized year-round rather than demand-driven, though a modest summer "
                 f"uptick aligns with known increases in rat surface activity during warm months.")
else:
    lines.append("*Monthly seasonality could not be computed.*\n")

lines.append("\n### 2.2 Day-of-Week Pattern\n")
if rodent_dow_data is not None and len(rodent_dow_data) > 0:
    lines.append("Inspections broken down by day of week (across all available years):\n")
    lines.append("| Day | Inspections | Relative to Mean | Level |")
    lines.append("|-----|-------------|------------------|-------|")
    mean_dow = rodent_dow_data['n'].mean()
    for _, row in rodent_dow_data.iterrows():
        rel = row['n'] / mean_dow
        if rel > 1.2:
            level = "**HIGH**"
        elif rel < 0.5:
            level = "very low"
        elif rel < 0.8:
            level = "low"
        else:
            level = "average"
        lines.append(f"| {row['day_name']} | {int(row['n']):,} | {rel:.2f}x | {level} |")

    top_days = rodent_dow_data.nlargest(3, 'n')['day_name'].tolist()
    low_days = rodent_dow_data.nsmallest(2, 'n')['day_name'].tolist()

    weekday_avg = rodent_dow_data[rodent_dow_data['day_name'].isin(['Mon','Tue','Wed','Thu','Fri'])]['n'].mean()
    weekend_avg = rodent_dow_data[rodent_dow_data['day_name'].isin(['Sat','Sun'])]['n'].mean()
    ratio = weekday_avg / max(weekend_avg, 1)

    lines.append(f"\nInspections are concentrated on **{', '.join(top_days)}**. "
                 f"Weekend volume ({', '.join(low_days)}) is just {1/ratio:.1%} of the weekday average, "
                 f"confirming this is a government work-week-driven operation. "
                 f"Tuesday and Wednesday show the highest single-day counts, consistent with "
                 f"inspectors being fully deployed mid-week.")
else:
    lines.append("*Day-of-week data could not be fetched.*\n")

if rodent_has_result:
    lines.append("\n### 2.3 Result Field\n")
    lines.append("The dataset includes a `result` field capturing inspection outcomes "
                 "(e.g., active rat signs, passed, failed). Seasonality of pass/fail rates "
                 "could reveal whether rats are harder to detect in certain months — "
                 "a more refined analysis is possible with this field.\n")

# ---- MTA ----
lines.append("\n---\n")
lines.append("## 3. MTA Ridership\n")
lines.append(f"**Primary dataset:** `{MTA_DATASET_ID}` — {MTA_NAME}  ")
lines.append("**API:** data.ny.gov (MTA data not available on data.cityofnewyork.us)  ")
lines.append("**Supplemental:** NYC Ferry Ridership (`t5n6-gx8c`) on data.cityofnewyork.us\n")

if mta_error:
    lines.append(f"**Note:** {mta_error}\n")

if mta_results_sorted:
    lines.append("### 3.1 Monthly Seasonality by Transit Mode\n")
    lines.append("Daily ridership aggregated to monthly totals; first and last (partial) months trimmed.\n")
    lines.append("| Rank | Mode | Months | Seasonal Strength | Peak Month | Pattern |")
    lines.append("|------|------|--------|-------------------|------------|---------|")
    for i, row in enumerate(mta_results_sorted, 1):
        s = row['seasonal_strength']
        if s >= 0.5:
            tag = " **HIGH**"
        elif s >= 0.2:
            tag = " MED"
        else:
            tag = " low"
        lines.append(
            f"| {i} | {row['mode']} | {row['n_months']} | {s:.3f}{tag} | {row['peak_month']} | {row['pattern']} |"
        )

    if ferry_strength is not None:
        s = ferry_strength
        tag = " **HIGH**" if s >= 0.5 else (" MED" if s >= 0.2 else " low")
        lines.append(
            f"| — | NYC Ferry (supplemental) | {ferry_months} | {s:.3f}{tag} "
            f"| {month_label(ferry_peak)} | {season_desc(ferry_peak)} |"
        )

    lines.append("\n**Key observations:**\n")

    strong = [r for r in mta_results_sorted if r['seasonal_strength'] >= 0.3]
    weak = [r for r in mta_results_sorted if r['seasonal_strength'] < 0.2]

    for r in strong[:5]:
        note = ""
        if 'subway' in r['field'].lower() or 'bus' in r['field'].lower():
            note = " — commuter ridership dips in summer (vacations) and holiday periods"
        elif 'lirr' in r['field'].lower() or 'metro_north' in r['field'].lower():
            note = " — leisure/reverse commute surges seasonally"
        elif 'bridge' in r['field'].lower():
            note = " — vehicle traffic follows summer road-trip and vacation patterns"
        lines.append(
            f"- **{r['mode']}** (strength {r['seasonal_strength']:.3f}): "
            f"{r['pattern']} (peak: {r['peak_month']}){note}"
        )

    if ferry_strength and ferry_strength >= 0.3:
        lines.append(
            f"- **NYC Ferry** (strength {ferry_strength:.3f}): "
            f"{season_desc(ferry_peak)} (peak: {month_label(ferry_peak)}) — "
            f"strongly seasonal as a leisure/fair-weather mode of transit"
        )

    if weak:
        lines.append(
            f"\nThe following modes show low seasonality (strength < 0.2): "
            + ", ".join(f"**{r['mode']}** ({r['seasonal_strength']:.3f})" for r in weak)
            + ". These are likely dominated by commuter patterns that remain consistent year-round, "
            "or were dominated by COVID-era noise during the 2020-2022 period."
        )
else:
    lines.append("*MTA monthly seasonality could not be computed — fetch failed.*\n")

# ---- SURPRISING FINDINGS ----
lines.append("\n---\n")
lines.append("## 4. Most Surprising Findings\n")

surprises = []

# Strongest complaint type
if complaint_results:
    top_ct = complaint_results[0]
    surprises.append(
        f"**Street noise is the *most* seasonal 311 complaint** "
        f"('{top_ct['complaint_type']}', strength {top_ct['seasonal_strength']:.3f}): "
        f"With {top_ct['total_volume']:,} complaints, it {top_ct['pattern']} (peak: {top_ct['peak_month']}). "
        f"This rivals HEAT/HOT WATER as a predictable seasonal surge — "
        f"NYC streets become dramatically louder once temperatures rise."
    )

    # HEAT/HOT WATER: very high strength + large volume
    heat = next((r for r in complaint_results if r['complaint_type'] == 'HEAT/HOT WATER'), None)
    if heat and heat['seasonal_strength'] >= 0.8:
        surprises.append(
            f"**HEAT/HOT WATER complaints are a near-perfect winter signal** "
            f"(strength {heat['seasonal_strength']:.3f}, peak {heat['peak_month']}): "
            f"With {heat['total_volume']:,} complaints and STL strength of {heat['seasonal_strength']:.3f}, "
            f"this is one of the strongest seasonal signals across all datasets — "
            f"making it a potential leading indicator for housing code enforcement needs."
        )

    # Blocked Driveway: high volume, low seasonality
    bd = next((r for r in complaint_results if r['complaint_type'] == 'Blocked Driveway'), None)
    if bd and bd['seasonal_strength'] < 0.15:
        surprises.append(
            f"**'Blocked Driveway' complaints show almost no seasonality** "
            f"(strength {bd['seasonal_strength']:.3f}) despite {bd['total_volume']:,} total complaints: "
            f"This suggests blocked driveways are a structural, year-round urban friction — "
            f"not driven by weather, events, or season. It is one of NYC's most *constant* irritants."
        )

# DHS seasonal patterns
dhs = next((r for r in agency_results if r['agency'] == 'DHS'), None)
if dhs:
    surprises.append(
        f"**DHS (Dept of Homeless Services) is the most seasonally predictable agency** "
        f"(strength {dhs['seasonal_strength']:.3f}, {dhs['pattern']}, peak {dhs['peak_month']}): "
        f"311 complaints routed to DHS spike sharply in summer. This may reflect increased "
        f"visibility of street homelessness and heat emergencies — a signal for targeted resource deployment."
    )

# Rodent weekday effect
if rodent_dow_data is not None and len(rodent_dow_data) > 0:
    weekday_avg = rodent_dow_data[rodent_dow_data['day_name'].isin(['Mon','Tue','Wed','Thu','Fri'])]['n'].mean()
    weekend_avg = rodent_dow_data[rodent_dow_data['day_name'].isin(['Sat','Sun'])]['n'].mean()
    ratio = weekday_avg / max(weekend_avg, 1)
    surprises.append(
        f"**Rodent inspections are ~{ratio:.0f}x more frequent on weekdays than weekends** "
        f"(weekday avg: {weekday_avg:,.0f} vs weekend avg: {weekend_avg:,.0f}): "
        f"NYC's rat inspection program is entirely a 9-to-5, Monday-Friday operation. "
        f"Any rat activity that emerges or escalates over the weekend goes uninspected for up to 48 hours "
        f"— a structural gap in the city's pest control surveillance."
    )

# Rodent low seasonality
if rodent_monthly_strength is not None and rodent_monthly_strength < 0.2:
    surprises.append(
        f"**Rodent inspection scheduling is surprisingly flat year-round** "
        f"(STL strength only {rodent_monthly_strength:.3f}): "
        f"Despite popular belief that rats are more active in summer, inspections are "
        f"distributed relatively evenly across months. This suggests the city's inspection cadence "
        f"is driven by administrative planning rather than rat activity levels."
    )

# MTA ferry vs subway
if ferry_strength and ferry_strength >= 0.5:
    sub_result = next((r for r in mta_results if 'subway' in r['field'].lower()), None)
    sub_strength_str = f"{sub_result['seasonal_strength']:.3f}" if sub_result else "N/A"
    surprises.append(
        f"**NYC Ferry ridership is dramatically more seasonal than the subway** "
        f"(Ferry strength {ferry_strength:.3f} vs Subway strength {sub_strength_str}): "
        f"The ferry {season_desc(ferry_peak)}, functioning almost as a seasonal amenity "
        f"rather than a core transit mode. The subway, by contrast, is used year-round with "
        f"much weaker seasonal variation."
    )

if not surprises:
    surprises.append("Insufficient data was returned to identify surprising findings. "
                     "See per-section results above.")

for s in surprises:
    lines.append(f"- {s}\n")

# ---- METHODOLOGY ----
lines.append("\n---\n")
lines.append("## 5. Methodology\n")
lines.append("### STL Decomposition\n")
lines.append("All seasonality scores use **STL (Seasonal-Trend decomposition using LOESS)** "
             "(Cleveland et al., 1990) with `robust=True` to down-weight outliers "
             "(e.g., COVID-era anomalies in MTA data).\n")
lines.append("**Seasonal strength formula:**\n")
lines.append("```\nStrength = max(0, 1 - Var(residual) / Var(seasonal + residual))\n```\n")
lines.append("A strength near 1 means the seasonal component dominates; near 0 means little structure.\n")
lines.append("### Data Filters\n")
lines.append("- 311 agencies: minimum 36 months of data, less than 30% missing months")
lines.append("- Missing months in agency series filled with the series median before STL fitting")
lines.append("- MTA: first and last months trimmed (often partial); COVID disruption affects 2020 baseline")
lines.append("- All API calls made without authentication (public endpoints)\n")
lines.append("### Data Sources\n")
lines.append("| Dataset | Source | Dataset ID |")
lines.append("|---------|--------|------------|")
lines.append("| 311 Service Requests | data.cityofnewyork.us | erm2-nwe9 |")
lines.append("| Rodent Inspections | data.cityofnewyork.us | p937-wjvj |")
lines.append("| MTA Daily Ridership | data.ny.gov | vxuj-8kew |")
lines.append("| NYC Ferry Ridership | data.cityofnewyork.us | t5n6-gx8c |\n")

report_text = "\n".join(lines)

output_path = "/home/karissawhiting/oracle-of-gotham/output/cyclical_report.md"
with open(output_path, 'w') as f:
    f.write(report_text)

print(f"\nReport written to: {output_path}")
print(f"Report: {len(report_text):,} chars, {len(lines)} lines")
